[dev]
  command = "vite"
  targetPort = 3000
  framework = "#custom"

[build]
  base = "./"
  publish = "dist"
  command = "yarn build"
  environment = { NODE_VERSION = "14.15.4" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  