[dev]
  command = "yarn dev"
  targetPort = 3000
  framework = "#custom"

[build]
  base = "./"
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200