[dev]
  command = "vite"
  targetPort = 3000
  framework = "#custom"

[build]
  base = "./"
  publish = "dist"
  command = "pnpm build"
  environment = { NODE_VERSION = "18.12.0", NODE_OPTIONS = "--max_old_space_size=4096" }

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202
  force = true

[[redirects]]
  from = "/api/flags"
  to = "https://atom-flags.horusdev.workers.dev"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200